<?php
$views = [
    'resources/views/admin/products/index.blade.php' => '@extends(\'layouts.app\') @section(\'content\') <h2>Products</h2> <a href="{{ route(\'admin.products.create\') }}" class="btn btn-primary mb-3">Add Product</a> <table class="table table-bordered"> <thead> <tr> <th>ID</th> <th>Image</th> <th>Name</th> <th>Category</th> <th>Price</th> <th>Stock</th> <th>Actions</th> </tr> </thead> <tbody> @foreach($products as $p) <tr> <td>{{ $p->id }}</td> <td>@if($p->image)<img src="{{ asset(\'storage/\'.$p->image) }}" width="50">@endif</td> <td>{{ $p->name }}</td> <td>{{ $p->category->name ?? \'\' }}</td> <td>${{ $p->price }}</td> <td>{{ $p->stock }}</td> <td> <a href="{{ route(\'admin.products.edit\', $p) }}" class="btn btn-sm btn-warning">Edit</a> <form action="{{ route(\'admin.products.destroy\', $p) }}" method="POST" class="d-inline"> @csrf @method(\'DELETE\') <button class="btn btn-sm btn-danger" onclick="return confirm(\'Delete?\')">Delete</button> </form> </td> </tr> @endforeach </tbody> </table> @endsection',
    'resources/views/admin/products/create.blade.php' => '@extends(\'layouts.app\') @section(\'content\') <h2>Add Product</h2> <form action="{{ route(\'admin.products.store\') }}" method="POST" enctype="multipart/form-data"> @csrf <div class="mb-3"> <label>Name</label> <input type="text" name="name" class="form-control" required value="{{ old(\'name\') }}"> @error(\'name\')<div class="text-danger">{{ $message }}</div>@enderror </div> <div class="mb-3"> <label>Category</label> <select name="category_id" class="form-select" required> <option value="">Select</option> @foreach($categories as $c) <option value="{{ $c->id }}">{{ $c->name }}</option> @endforeach </select> </div> <div class="mb-3"> <label>Price</label> <input type="number" step="0.01" name="price" class="form-control" required value="{{ old(\'price\') }}"> </div> <div class="mb-3"> <label>Stock</label> <input type="number" name="stock" class="form-control" required value="{{ old(\'stock\') }}"> </div> <div class="mb-3"> <label>Description</label> <textarea name="description" class="form-control">{{ old(\'description\') }}</textarea> </div> <div class="mb-3"> <label>Image</label> <input type="file" name="image" class="form-control"> </div> <button class="btn btn-primary">Save</button> </form> @endsection',
    'resources/views/admin/products/edit.blade.php' => '@extends(\'layouts.app\') @section(\'content\') <h2>Edit Product</h2> <form action="{{ route(\'admin.products.update\', $product) }}" method="POST" enctype="multipart/form-data"> @csrf @method(\'PUT\') <div class="mb-3"> <label>Name</label> <input type="text" name="name" class="form-control" required value="{{ old(\'name\', $product->name) }}"> </div> <div class="mb-3"> <label>Category</label> <select name="category_id" class="form-select" required> <option value="">Select</option> @foreach($categories as $c) <option value="{{ $c->id }}" {{ $product->category_id == $c->id ? \'selected\' : \'\' }}>{{ $c->name }}</option> @endforeach </select> </div> <div class="mb-3"> <label>Price</label> <input type="number" step="0.01" name="price" class="form-control" required value="{{ old(\'price\', $product->price) }}"> </div> <div class="mb-3"> <label>Stock</label> <input type="number" name="stock" class="form-control" required value="{{ old(\'stock\', $product->stock) }}"> </div> <div class="mb-3"> <label>Description</label> <textarea name="description" class="form-control">{{ old(\'description\', $product->description) }}</textarea> </div> <div class="mb-3"> <label>Image</label> <input type="file" name="image" class="form-control"> @if($product->image)<img src="{{ asset(\'storage/\'.$product->image) }}" width="100" class="mt-2">@endif </div> <button class="btn btn-primary">Update</button> </form> @endsection',
    
    'resources/views/admin/categories/index.blade.php' => '@extends(\'layouts.app\') @section(\'content\') <h2>Categories</h2> <a href="{{ route(\'admin.categories.create\') }}" class="btn btn-primary mb-3">Add Category</a> <table class="table table-bordered"> <thead> <tr> <th>ID</th> <th>Name</th> <th>Description</th> <th>Actions</th> </tr> </thead> <tbody> @foreach($categories as $c) <tr> <td>{{ $c->id }}</td> <td>{{ $c->name }}</td> <td>{{ $c->description }}</td> <td> <a href="{{ route(\'admin.categories.edit\', $c) }}" class="btn btn-sm btn-warning">Edit</a> <form action="{{ route(\'admin.categories.destroy\', $c) }}" method="POST" class="d-inline"> @csrf @method(\'DELETE\') <button class="btn btn-sm btn-danger" onclick="return confirm(\'Delete?\')">Delete</button> </form> </td> </tr> @endforeach </tbody> </table> @endsection',
    'resources/views/admin/categories/create.blade.php' => '@extends(\'layouts.app\') @section(\'content\') <h2>Add Category</h2> <form action="{{ route(\'admin.categories.store\') }}" method="POST"> @csrf <div class="mb-3"> <label>Name</label> <input type="text" name="name" class="form-control" required value="{{ old(\'name\') }}"> @error(\'name\')<div class="text-danger">{{ $message }}</div>@enderror </div> <div class="mb-3"> <label>Description</label> <textarea name="description" class="form-control">{{ old(\'description\') }}</textarea> </div> <button class="btn btn-primary">Save</button> </form> @endsection',
    'resources/views/admin/categories/edit.blade.php' => '@extends(\'layouts.app\') @section(\'content\') <h2>Edit Category</h2> <form action="{{ route(\'admin.categories.update\', $category) }}" method="POST"> @csrf @method(\'PUT\') <div class="mb-3"> <label>Name</label> <input type="text" name="name" class="form-control" required value="{{ old(\'name\', $category->name) }}"> </div> <div class="mb-3"> <label>Description</label> <textarea name="description" class="form-control">{{ old(\'description\', $category->description) }}</textarea> </div> <button class="btn btn-primary">Update</button> </form> @endsection',

    'resources/views/admin/orders/index.blade.php' => '@extends(\'layouts.app\') @section(\'content\') <h2>All Orders</h2> <table class="table table-bordered"> <thead> <tr> <th>ID</th> <th>Customer</th> <th>Total</th> <th>Status</th> <th>Date</th> <th>Actions</th> </tr> </thead> <tbody> @foreach($orders as $o) <tr> <td>{{ $o->id }}</td> <td>{{ $o->user->name ?? \'\' }}</td> <td>${{ $o->total_price }}</td> <td> <form action="{{ route(\'admin.orders.update\', $o) }}" method="POST" class="d-flex gap-2"> @csrf @method(\'PUT\') <select name="status" class="form-select form-select-sm"> <option value="pending" {{ $o->status == \'pending\' ? \'selected\' : \'\' }}>Pending</option> <option value="processing" {{ $o->status == \'processing\' ? \'selected\' : \'\' }}>Processing</option> <option value="delivered" {{ $o->status == \'delivered\' ? \'selected\' : \'\' }}>Delivered</option> <option value="cancelled" {{ $o->status == \'cancelled\' ? \'selected\' : \'\' }}>Cancelled</option> </select> <button class="btn btn-sm btn-primary">Update</button> </form> </td> <td>{{ $o->created_at->format(\'Y-m-d\') }}</td> <td></td> </tr> @endforeach </tbody> </table> @endsection',

    'resources/views/cart.blade.php' => '@extends(\'layouts.app\') @section(\'content\') <h2>Shopping Cart</h2> @if($carts->isEmpty()) <p>Your cart is empty.</p> @else <table class="table"> <thead> <tr> <th>Product</th> <th>Price</th> <th>Quantity</th> <th>Total</th> <th>Actions</th> </tr> </thead> <tbody> @php $total = 0; @endphp @foreach($carts as $c) @php $total += $c->product->price * $c->quantity; @endphp <tr> <td>{{ $c->product->name }}</td> <td>${{ $c->product->price }}</td> <td> <form action="{{ route(\'cart.update\', $c) }}" method="POST" class="d-flex gap-2"> @csrf @method(\'PUT\') <input type="number" name="quantity" value="{{ $c->quantity }}" min="1" max="{{ $c->product->stock }}" class="form-control" style="width: 80px"> <button class="btn btn-sm btn-secondary">Update</button> </form> </td> <td>${{ $c->product->price * $c->quantity }}</td> <td> <form action="{{ route(\'cart.remove\', $c) }}" method="POST"> @csrf @method(\'DELETE\') <button class="btn btn-sm btn-danger">Remove</button> </form> </td> </tr> @endforeach </tbody> </table> <h4>Total: ${{ $total }}</h4> <hr> <h4>Checkout</h4> <form action="{{ route(\'order.place\') }}" method="POST"> @csrf <div class="mb-3"> <label>Delivery Address</label> <textarea name="address" class="form-control" required></textarea> </div> <button class="btn btn-success">Place Order</button> </form> @endif @endsection',

    'resources/views/orders/index.blade.php' => '@extends(\'layouts.app\') @section(\'content\') <h2>My Orders</h2> <table class="table table-bordered"> <thead> <tr> <th>Order ID</th> <th>Total Price</th> <th>Status</th> <th>Delivery Address</th> <th>Date</th> </tr> </thead> <tbody> @foreach($orders as $o) <tr> <td>{{ $o->id }}</td> <td>${{ $o->total_price }}</td> <td><span class="badge bg-{{ $o->status == \'delivered\' ? \'success\' : ($o->status == \'cancelled\' ? \'danger\' : \'warning\') }}">{{ ucfirst($o->status) }}</span></td> <td>{{ $o->address }}</td> <td>{{ $o->created_at->format(\'Y-m-d H:i\') }}</td> </tr> @endforeach </tbody> </table> @endsection',
];

foreach ($views as $path => $content) {
    $dir = dirname(__DIR__ . '/' . $path);
    if (!is_dir($dir)) mkdir($dir, 0777, true);
    file_put_contents(__DIR__ . '/' . $path, $content);
}
