<?php
$controllers = [
    'app/Http/Controllers/HomeController.php' => "<?php\nnamespace App\Http\Controllers;\nuse App\Models\Product;\nuse App\Models\Category;\nuse Illuminate\Http\Request;\nclass HomeController extends Controller {\n    public function index(Request \$request) {\n        \$query = Product::query();\n        if(\$request->has('search')) {\n            \$query->where('name', 'like', '%'.\$request->search.'%');\n        }\n        if(\$request->has('category_id') && \$request->category_id != '') {\n            \$query->where('category_id', \$request->category_id);\n        }\n        \$products = \$query->get();\n        \$categories = Category::all();\n        return view('home', compact('products', 'categories'));\n    }\n    public function show(Product \$product) {\n        return view('product', compact('product'));\n    }\n}",
    'app/Http/Controllers/CartController.php' => "<?php\nnamespace App\Http\Controllers;\nuse App\Models\Cart;\nuse App\Models\Product;\nuse Illuminate\Http\Request;\nclass CartController extends Controller {\n    public function index() {\n        \$carts = Cart::where('user_id', auth()->id())->with('product')->get();\n        return view('cart', compact('carts'));\n    }\n    public function add(Request \$request, Product \$product) {\n        \$cart = Cart::where('user_id', auth()->id())->where('product_id', \$product->id)->first();\n        if (\$cart) {\n            \$cart->quantity += \$request->quantity ?? 1;\n            \$cart->save();\n        } else {\n            Cart::create([\n                'user_id' => auth()->id(),\n                'product_id' => \$product->id,\n                'quantity' => \$request->quantity ?? 1\n            ]);\n        }\n        return redirect()->route('cart.index')->with('success', 'Added to cart');\n    }\n    public function update(Request \$request, Cart \$cart) {\n        \$cart->update(['quantity' => \$request->quantity]);\n        return back();\n    }\n    public function remove(Cart \$cart) {\n        \$cart->delete();\n        return back();\n    }\n}",
    'app/Http/Controllers/OrderController.php' => "<?php\nnamespace App\Http\Controllers;\nuse App\Models\Order;\nuse App\Models\OrderItem;\nuse App\Models\Cart;\nuse Illuminate\Http\Request;\nclass OrderController extends Controller {\n    public function index() {\n        \$orders = Order::where('user_id', auth()->id())->get();\n        return view('orders.index', compact('orders'));\n    }\n    public function store(Request \$request) {\n        \$request->validate(['address' => 'required']);\n        \$carts = Cart::where('user_id', auth()->id())->get();\n        if (\$carts->isEmpty()) return back()->with('error', 'Cart is empty');\n        \$total = 0;\n        foreach (\$carts as \$cart) { \$total += \$cart->product->price * \$cart->quantity; }\n        \$order = Order::create(['user_id' => auth()->id(), 'total_price' => \$total, 'address' => \$request->address]);\n        foreach (\$carts as \$cart) {\n            OrderItem::create(['order_id' => \$order->id, 'product_id' => \$cart->product_id, 'quantity' => \$cart->quantity, 'price' => \$cart->product->price]);\n            \$cart->product->decrement('stock', \$cart->quantity);\n            \$cart->delete();\n        }\n        return redirect()->route('orders.index')->with('success', 'Order placed successfully');\n    }\n}",
    'app/Http/Controllers/CategoryController.php' => "<?php\nnamespace App\Http\Controllers;\nuse App\Models\Category;\nuse Illuminate\Http\Request;\nclass CategoryController extends Controller {\n    public function index() { return view('admin.categories.index', ['categories' => Category::all()]); }\n    public function create() { return view('admin.categories.create'); }\n    public function store(Request \$request) {\n        \$request->validate(['name' => 'required']);\n        Category::create(\$request->all());\n        return redirect()->route('admin.categories.index');\n    }\n    public function edit(Category \$category) { return view('admin.categories.edit', compact('category')); }\n    public function update(Request \$request, Category \$category) {\n        \$request->validate(['name' => 'required']);\n        \$category->update(\$request->all());\n        return redirect()->route('admin.categories.index');\n    }\n    public function destroy(Category \$category) { \$category->delete(); return back(); }\n}",
    'app/Http/Controllers/ProductController.php' => "<?php\nnamespace App\Http\Controllers;\nuse App\Models\Product;\nuse App\Models\Category;\nuse Illuminate\Http\Request;\nuse Illuminate\Support\Facades\Storage;\nclass ProductController extends Controller {\n    public function index() { return view('admin.products.index', ['products' => Product::with('category')->get()]); }\n    public function create() { return view('admin.products.create', ['categories' => Category::all()]); }\n    public function store(Request \$request) {\n        \$data = \$request->validate(['name' => 'required', 'price' => 'required|numeric', 'stock' => 'required|integer', 'category_id' => 'required', 'description' => 'nullable', 'image' => 'nullable|image']);\n        if (\$request->hasFile('image')) \$data['image'] = \$request->file('image')->store('products', 'public');\n        Product::create(\$data);\n        return redirect()->route('admin.products.index');\n    }\n    public function edit(Product \$product) { return view('admin.products.edit', ['product' => \$product, 'categories' => Category::all()]); }\n    public function update(Request \$request, Product \$product) {\n        \$data = \$request->validate(['name' => 'required', 'price' => 'required|numeric', 'stock' => 'required|integer', 'category_id' => 'required', 'description' => 'nullable', 'image' => 'nullable|image']);\n        if (\$request->hasFile('image')) {\n            if (\$product->image) Storage::disk('public')->delete(\$product->image);\n            \$data['image'] = \$request->file('image')->store('products', 'public');\n        }\n        \$product->update(\$data);\n        return redirect()->route('admin.products.index');\n    }\n    public function destroy(Product \$product) { if (\$product->image) Storage::disk('public')->delete(\$product->image); \$product->delete(); return back(); }\n}",
    'app/Http/Controllers/Admin/DashboardController.php' => "<?php\nnamespace App\Http\Controllers\Admin;\nuse App\Http\Controllers\Controller;\nuse App\Models\Product;\nuse App\Models\Order;\nuse App\Models\User;\nclass DashboardController extends Controller {\n    public function index() {\n        \$totalProducts = Product::count();\n        \$totalOrders = Order::count();\n        \$totalCustomers = User::where('role', 'customer')->count();\n        \$totalRevenue = Order::sum('total_price');\n        \$lowStock = Product::where('stock', '<', 5)->get();\n        \$recentOrders = Order::latest()->take(5)->get();\n        return view('admin.dashboard', compact('totalProducts', 'totalOrders', 'totalCustomers', 'totalRevenue', 'lowStock', 'recentOrders'));\n    }\n}",
    'app/Http/Controllers/Admin/OrderController.php' => "<?php\nnamespace App\Http\Controllers\Admin;\nuse App\Http\Controllers\Controller;\nuse App\Models\Order;\nuse Illuminate\Http\Request;\nclass OrderController extends Controller {\n    public function index() { return view('admin.orders.index', ['orders' => Order::latest()->get()]); }\n    public function update(Request \$request, Order \$order) {\n        \$order->update(['status' => \$request->status]);\n        return back()->with('success', 'Status updated');\n    }\n}",
];

foreach ($controllers as $path => $content) {
    $dir = dirname(__DIR__ . '/' . $path);
    if (!is_dir($dir)) mkdir($dir, 0777, true);
    file_put_contents(__DIR__ . '/' . $path, $content);
}
