<?php
$views = [
    'resources/views/layouts/app.blade.php' => '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Toy Store</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"></head><body><nav class="navbar navbar-expand-lg navbar-dark bg-primary"><div class="container"><a class="navbar-brand" href="{{ route(\'home\') }}">Toy Store</a><div class="collapse navbar-collapse"><ul class="navbar-nav ms-auto">@auth @if(auth()->user()->role == \'admin\') <li class="nav-item"><a class="nav-link" href="{{ route(\'admin.dashboard\') }}">Admin Dashboard</a></li> @else <li class="nav-item"><a class="nav-link" href="{{ route(\'cart.index\') }}">Cart</a></li> <li class="nav-item"><a class="nav-link" href="{{ route(\'orders.index\') }}">My Orders</a></li> @endif <li class="nav-item"><form method="POST" action="{{ route(\'logout\') }}">@csrf<button type="submit" class="btn btn-link nav-link">Logout</button></form></li> @else <li class="nav-item"><a class="nav-link" href="{{ route(\'login\') }}">Login</a></li> <li class="nav-item"><a class="nav-link" href="{{ route(\'register\') }}">Register</a></li> @endauth</ul></div></div></nav><main class="container mt-4">@if(session(\'success\'))<div class="alert alert-success">{{ session(\'success\') }}</div>@endif @if(session(\'error\'))<div class="alert alert-danger">{{ session(\'error\') }}</div>@endif @yield(\'content\')</main><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script></body></html>',
    'resources/views/home.blade.php' => '@extends(\'layouts.app\') @section(\'content\') <h2>Toys</h2> <form class="mb-4 d-flex gap-2" method="GET"> <input type="text" name="search" class="form-control" placeholder="Search..." value="{{ request(\'search\') }}"> <select name="category_id" class="form-select"> <option value="">All Categories</option> @foreach($categories as $c) <option value="{{ $c->id }}" {{ request(\'category_id\') == $c->id ? \'selected\' : \'\' }}>{{ $c->name }}</option> @endforeach </select> <button class="btn btn-primary">Filter</button> </form> <div class="row"> @foreach($products as $p) <div class="col-md-3 mb-4"><div class="card"><div class="card-body"><h5 class="card-title">{{ $p->name }}</h5><p class="card-text">${{ $p->price }}</p><a href="{{ route(\'product.show\', $p) }}" class="btn btn-sm btn-outline-primary">View</a></div></div></div> @endforeach </div> @endsection',
    'resources/views/product.blade.php' => '@extends(\'layouts.app\') @section(\'content\') <div class="row"><div class="col-md-6"> @if($product->image) <img src="{{ asset(\'storage/\'.$product->image) }}" class="img-fluid"> @else <div class="bg-secondary text-white p-5 text-center">No Image</div> @endif </div><div class="col-md-6"> <h2>{{ $product->name }}</h2> <h4>${{ $product->price }}</h4> <p>Stock: {{ $product->stock }}</p> <p>{{ $product->description }}</p> @if($product->stock > 0) <form action="{{ route(\'cart.add\', $product) }}" method="POST" class="d-flex gap-2"> @csrf <input type="number" name="quantity" value="1" min="1" max="{{ $product->stock }}" class="form-control w-25"> <button class="btn btn-success">Add to Cart</button> </form> @else <span class="badge bg-danger">Out of Stock</span> @endif </div></div> @endsection',
    'resources/views/admin/dashboard.blade.php' => '@extends(\'layouts.app\') @section(\'content\') <h2>Admin Dashboard</h2> <div class="row mb-4"> <div class="col-md-3"><div class="card bg-info text-white"><div class="card-body"><h5>Products</h5><h3>{{ $totalProducts }}</h3></div></div></div> <div class="col-md-3"><div class="card bg-success text-white"><div class="card-body"><h5>Orders</h5><h3>{{ $totalOrders }}</h3></div></div></div> <div class="col-md-3"><div class="card bg-warning text-dark"><div class="card-body"><h5>Customers</h5><h3>{{ $totalCustomers }}</h3></div></div></div> <div class="col-md-3"><div class="card bg-danger text-white"><div class="card-body"><h5>Revenue</h5><h3>${{ $totalRevenue }}</h3></div></div></div> </div> <div class="mb-3 d-flex gap-2"> <a href="{{ route(\'admin.products.index\') }}" class="btn btn-primary">Manage Products</a> <a href="{{ route(\'admin.categories.index\') }}" class="btn btn-primary">Manage Categories</a> <a href="{{ route(\'admin.orders.index\') }}" class="btn btn-primary">Manage Orders</a> </div> @if($lowStock->count() > 0) <div class="alert alert-warning"> <h5>Low Stock Alerts!</h5> <ul> @foreach($lowStock as $p) <li>{{ $p->name }} ({{ $p->stock }} left)</li> @endforeach </ul> </div> @endif @endsection',
];

foreach ($views as $path => $content) {
    $dir = dirname(__DIR__ . '/' . $path);
    if (!is_dir($dir)) mkdir($dir, 0777, true);
    file_put_contents(__DIR__ . '/' . $path, $content);
}
